### ISSUE TITLE
Match Interface Docs

### ISSUE THREAD

**Issue by bdaroz** [FIRSTRobotics/fms-manual#45]
The Match Play/Test docs at [`source/event-manager/match-play-test/interface.rst`](https://github.com/FIRSTRobotics/fms-manual/blob/d78bae76a591247e6b4aca8dd44a0e2e24627824/source/event-manager/match-play-test/interface.rst) have inconsistent images and labels.

The top image shows the new interface, but under `Station Status` is a screenshot (with numbered callouts) from the old interface. Additionally the numbered callouts are accurate only through 6, callouts 7 and 8 are renumbered 1 and 2 under the `Team` section.

**Comment by alexherreid** [comment]
Hi there- we are waiting on new screenshots from when there is a full set of robots/status info at week 0. The concept and data available is still accurate as described.

**Comment by Jpatterson780** [comment]
Brian - Good catch on the numbered callouts. We can get that corrected, likely with the new screenshots that Alex mentioned.
