### ISSUE TITLE
Example image in Status Tab article is inconsistent with note

### ISSUE THREAD

**Issue by nlaverdure** [FIRSTRobotics/fms-manual#48]
The Status Tab article includes a note which says:

> It is important to remember that items can only “go green” if the items to the left of it are already “green.” For instance, a roboRIO will not be green unless the Radio is already green.

However, the example image shows Red 3 - 6 with red radio and green roboRIO, which is inconsistent with the note.

![image](https://user-images.githubusercontent.com/41549690/221868370-c7a13453-849a-4049-9d99-43b3bc72186f.png)

**Comment by alexherreid** [comment]
examples getting swapped out
